---
  - name: build_Boxfuse-hello.war
    hosts: buildServer
    become: yes
  
    tasks:
    - name: Ensure git package is present
      apt:
        name: git
        state: present
    - name: Ensure boxfuse direcotry is present
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /var/boxfuse
    - name: Ensure maven package is present
      apt:
        name: maven
        state: present
    - name: assembly_App
      shell: "mvn package"
      args:
        chdir: /var/boxfuse        
  - name: start tomcat   
    hosts: prodServer
    become: yes

    tasks:
    - name: Ensure tomcat is present
      apt:
        name: tomcat8
        state: present
    - name: Ensure tomcat service is started
      service:
        name: tomcat8
        state: started
    - name: synchronization_app
      synchronize: src=/var/boxfuse/target/hello-1.0.war dest=/var/lib/tomcat8/webapps/     
    